export const NEW = {
  "/": ["Ortex Industries | Custom Lanyards, Badges & Corporate Gifts", "Delhi manufacturer of custom MDF and acrylic products, lanyards, badges, exam boards and corporate gifts. OEM and white label, PAN India delivery and export."],
  "/about": ["About Ortex Industries | Custom Manufacturer in Delhi", "How Ortex Industries started, why brands across India trust us, and the in-house cutting, printing and engraving behind every order we manufacture."],
  "/products": ["Custom MDF, Acrylic, Lanyard & Badge Products | Ortex", "Browse Ortex Industries' custom products: MDF and acrylic items, lanyards, badges, exam boards and corporate gifts, all branded in-house with GST quotations."],
  "/industries": ["Industries We Serve | Ortex Industries", "Custom products for corporates, schools, universities, government departments, hospitals and event companies, manufactured in-house by Ortex Industries."],
  "/oem": ["OEM & White Label Manufacturing | Ortex Industries", "Contract OEM and white-label manufacturing of MDF, acrylic, lanyards, badges and merchandise, made in-house under your brand with factory-direct pricing."],
  "/work": ["Our Work: Custom Products We Made | Ortex Industries", "Real production photos from Ortex Industries: custom keychains, wall clocks, exam boards, badges, lanyards, fridge magnets and promotional merchandise."],
  "/contact": ["Contact Ortex Industries | Get a Custom Product Quote", "Get a factory-direct quote for custom MDF, acrylic, lanyards, badges and corporate gifts. Call +91-9211947188, email sales@ortexindustries.in or WhatsApp us."],
  "/quote": ["Get a Quote for Custom Products | Ortex Industries", "Build a request from the Ortex Industries catalogue: pick MDF, acrylic, lanyard, badge or gift products, set quantities, and receive a formal GST quotation."],
  "/faq": ["Custom Manufacturing FAQs: MOQ, Artwork | Ortex Industries", "Answers on minimum order quantities, samples, artwork files, materials, delivery times, OEM production and payment for custom orders at Ortex Industries."],
  "/privacy": ["Privacy Policy | Ortex Industries", "How Ortex Industries collects, uses and protects the information you share through our website, quote requests, enquiry forms and custom manufacturing orders."],
  "/terms": ["Terms of Service | Ortex Industries", "The terms that govern use of the Ortex Industries website, quote requests and custom manufacturing orders, including artwork approval, payment and delivery."],
  "/cookies": ["Cookie Policy | Ortex Industries", "How the Ortex Industries website uses cookies and browser storage, what each one does, and how to accept, decline or clear them at any time."],
  "/acceptable-use": ["Acceptable Use Policy | Ortex Industries", "Rules for using the Ortex Industries website and uploading artwork: prohibited content, trademarks and the rights you confirm when you send us a design."],
}
export const CAT = {
  keychains: ["Custom Keychain Manufacturer in India | Ortex Industries", "Bulk custom keychains made in-house: UV-printed acrylic, debossed leather, moulded silicone and PVC, and satin. Factory-direct pricing with volume discounts."],
  "acrylic-products": ["Custom Acrylic Products Manufacturer | Ortex Industries", "Custom acrylic desk standees, name display holders, card holders, paperweights and dashboard idols. Cast acrylic, UV-printed and laser-cut in-house."],
  "mdf-products": ["Custom MDF Products Manufacturer | Ortex Industries", "Custom MDF award trophies, examination pads, key holders and custom-shape fridge magnets, CNC-routed, laser-engraved and UV-printed in-house in Delhi."],
  lanyards: ["Custom Lanyard Manufacturer in India | Ortex Industries", "Full-colour sublimation and satin-printed lanyards made in bulk: 16 mm and 20 mm widths, metal hooks and safety breakaway clasps. Factory-direct pricing."],
  badges: ["Custom Badge Manufacturer: Metal & Button | Ortex Industries", "Custom badges in bulk: engraved brass name badges with magnet backing, enamel lapel pins, printed button badges, moulded pin badges and LED badges."],
  "examination-boards": ["Examination Board Manufacturer | Ortex Industries", "Bulk examination boards for schools and institutions: PVC A4 clipboards, foldable exam boards with storage, and 6 mm MDF clipboards with custom branding."],
  "wall-clocks": ["Promotional Wall Clock Manufacturer | Ortex Industries", "Custom-branded wall clocks in bulk: 8-inch and 7.5-inch promotional clocks, 15-inch designer clocks, wooden and acrylic clocks with quartz movements."],
  "fridge-magnets": ["Custom Fridge Magnet Manufacturer | Ortex Industries", "Custom fridge magnets made in bulk: UV-printed MDF in any shape, transparent acrylic, soft PVC with 2D/3D embossing, and laser-engraved wooden magnets."],
  "corporate-gifts": ["Corporate Gifts Manufacturer in India | Ortex Industries", "Corporate gifts branded in-house: insulated steel bottles and flasks, lunch box sets, diary and pen gift sets. Factory-direct pricing with GST invoicing."],
  "flags-banners": ["Custom Flag Manufacturer in India | Ortex Industries", "Custom printed polyester flags made in bulk: 3×5 ft flags with double-side printing and 2×3 ft party or election flags on wooden sticks."],
  clipboards: ["Custom Clipboard Manufacturer | Ortex Industries", "Custom A4 MDF clipboards with spring clips, branded front and back, manufactured in-house for institutions, events and corporate stationery programmes."],
  "promotional-merchandise": ["Promotional Merchandise Manufacturer | Ortex Industries", "Bulk promotional merchandise: cotton twill caps with embroidery or printing and sublimation-printed mobile popsockets, at factory-direct pricing."],
}
