import * as Notifications from "expo-notifications"
import { Platform } from "react-native"

import type { AppNotification, NotificationActionId } from "@/domain/notifications"

/**
 * The notification shade.
 *
 * These are LOCAL notifications, not remote push, and that is a design decision
 * rather than a shortcut. Everything this app would notify about is derived
 * (see domain/notifications.ts) from rows it already holds and already watches
 * over Supabase realtime, so the phone can post the same message itself with no
 * FCM/APNs credentials, no device-token table, no server fan-out and nothing new
 * to keep in step with the console. The cost is honest and worth stating: the
 * app must be running (foreground, or alive in the background) for a signal to
 * reach the shade. Waking a killed app needs FCM, which is a separate piece of
 * work — see docs in Ortex.Mobile/README.md.
 *
 * Every notification carries its ACTIONS, because on a field-sales phone the
 * answer to "new lead from Rakesh, 5000 lanyards" is to ring Rakesh, and that
 * should not require opening the app to find the number. The buttons are wired
 * in features/notifications/useNotificationEngine.ts, which owns the response
 * listener; this file owns the OS plumbing only.
 */

/** Categories — the sets of action buttons a notification can be posted with. */
export const CATEGORY_WITH_PHONE = "ortex.lead.phone"
export const CATEGORY_PLAIN = "ortex.lead.plain"

/**
 * Android channels. Separate, so a rep can silence reminders and keep leads.
 *
 * The ids carry a version because Android fixes a channel's sound and vibration
 * the moment it is first created on a handset; changing them in code does
 * nothing to a channel that already exists. v3 is the `ortex_ring` sound
 * (res/raw, generated by scripts/notification-sound.mjs) and the strong pattern
 * below (v2 was created on a dev handset by a half-applied hot reload with the
 * old settings, and is retired with v1); older ids are deleted in
 * `configurePush` so Settings shows one
 * "Leads" and one "Reminders", not two of each.
 */
export const CHANNEL_LEADS = "leads_v3"
export const CHANNEL_REMINDERS = "reminders_v3"
const RETIRED_CHANNELS = ["leads", "reminders", "leads_v2", "reminders_v2"]

/** The file name in android/app/src/main/res/raw (and the iOS bundle, once added). */
export const RING_SOUND = "ortex_ring.wav"

/**
 * Strong, in the rhythm of the ring: buzz-buzz, pause, buzz-buzz (ms, starting
 * with the delay). Long pulses rather than taps, so it is felt through a pocket,
 * like a delivery app's order alert.
 */
const LEAD_VIBRATION = [0, 450, 120, 450, 350, 450, 120, 700]
const REMINDER_VIBRATION = [0, 350, 150, 350]

/** What the OS hands back in a response, and what the engine acts on. */
export type PushPayload = {
  id: string
  target: AppNotification["target"]
  phone: string
  title: string
}

/** The sample's id, special-cased by the engine's response handler. */
export const TEST_NOTIFICATION_ID = "ortex.test"

let configured = false

// A tapped or actioned notification should open the app, not just dismiss.
//
// A REMOTE lead (lib/remotePush.ts, sent by the push-notify function) that lands
// while the app is in the foreground is not shown: the engine posts its own copy
// of the same lead, with the Call / WhatsApp buttons the server's cannot carry,
// and reloads the collection on arrival so it does so even if realtime missed
// the row. In the background Android draws the server's copy itself and this
// handler is never asked.
Notifications.setNotificationHandler({
  handleNotification: async (notification) => {
    const remote = isRemoteLead(notification)
    return {
      shouldShowBanner: !remote,
      shouldShowList: !remote,
      shouldPlaySound: !remote,
      shouldSetBadge: true,
    }
  },
})

/** A lead sent by the server (push-notify) rather than posted by this phone. */
export function isRemoteLead(notification: Notifications.Notification): boolean {
  const data = notification.request.content.data as Record<string, unknown> | undefined
  return data?.remote === "1"
}

/**
 * Channels and categories, once per process. Android needs the channel to exist
 * BEFORE the first notification is posted — one created afterwards does not
 * retro-apply its importance, so the first lead of the install would arrive
 * silent and every later one would chime.
 */
export async function configurePush(): Promise<void> {
  if (configured) return
  configured = true

  if (Platform.OS === "android") {
    for (const id of RETIRED_CHANNELS) {
      await Notifications.deleteNotificationChannelAsync(id).catch(() => {})
    }
    await Notifications.setNotificationChannelAsync(CHANNEL_LEADS, {
      name: "Leads",
      description: "New enquiries and voice calls from the website",
      // MAX, not HIGH: a new lead heads up over whatever is on screen, the way
      // an order does on a rider's phone.
      importance: Notifications.AndroidImportance.MAX,
      sound: RING_SOUND,
      enableVibrate: true,
      vibrationPattern: LEAD_VIBRATION,
      lockscreenVisibility: Notifications.AndroidNotificationVisibility.PUBLIC,
      lightColor: "#2F50E4",
    }).catch(() => {})
    await Notifications.setNotificationChannelAsync(CHANNEL_REMINDERS, {
      name: "Reminders",
      description: "Enquiries going cold and quotations about to expire",
      importance: Notifications.AndroidImportance.HIGH,
      sound: RING_SOUND,
      enableVibrate: true,
      vibrationPattern: REMINDER_VIBRATION,
      lightColor: "#2F50E4",
    }).catch(() => {})
  }

  // `opensAppToForeground: false` on Call and WhatsApp is the point of them:
  // the rep taps Call in the shade and the dialler opens, without the app
  // painting a screen they did not ask for on the way.
  await Notifications.setNotificationCategoryAsync(CATEGORY_WITH_PHONE, [
    { identifier: "call", buttonTitle: "Call", options: { opensAppToForeground: false } },
    { identifier: "whatsapp", buttonTitle: "WhatsApp", options: { opensAppToForeground: false } },
    { identifier: "open", buttonTitle: "Open", options: { opensAppToForeground: true } },
  ]).catch(() => {})
  await Notifications.setNotificationCategoryAsync(CATEGORY_PLAIN, [
    { identifier: "open", buttonTitle: "Open", options: { opensAppToForeground: true } },
  ]).catch(() => {})
}

/**
 * Ask for permission, once the rep has actually seen what the app does.
 * Android 13+ needs POST_NOTIFICATIONS at runtime; below that, and on a device
 * that already granted it, this resolves immediately.
 */
export async function ensurePushPermission(): Promise<boolean> {
  try {
    const current = await Notifications.getPermissionsAsync()
    if (current.granted) return true
    // `canAskAgain: false` means the rep denied it in the OS — asking again is
    // a no-op that returns denied, so report it rather than loop.
    if (!current.canAskAgain) return false
    const next = await Notifications.requestPermissionsAsync()
    return next.granted
  } catch {
    return false
  }
}

export async function pushPermissionGranted(): Promise<boolean> {
  try {
    return (await Notifications.getPermissionsAsync()).granted
  } catch {
    return false
  }
}

const REMINDER_KINDS = new Set(["enquiry-stale", "quotation-expiring", "quotation-expired"])

/**
 * Post one notification. `trigger: null` means "now" — these are already-true
 * facts about leads that have landed, never a schedule.
 */
export async function presentNotification(item: AppNotification): Promise<void> {
  const payload: PushPayload = {
    id: item.id,
    target: item.target,
    phone: item.phone,
    title: item.title,
  }

  await Notifications.scheduleNotificationAsync({
    content: {
      title: item.push.title,
      body: item.push.body,
      // The long-form body Android expands to, so a lead with four items is
      // readable without opening anything.
      subtitle: item.module,
      data: payload as unknown as Record<string, unknown>,
      categoryIdentifier: item.phone ? CATEGORY_WITH_PHONE : CATEGORY_PLAIN,
      // Android plays the CHANNEL's sound and ignores this; iOS plays this file
      // once it is in the app bundle, and the default sound until then.
      sound: RING_SOUND,
      // Urgent rows (a complaint, an expired quote) get the loud treatment.
      priority: item.urgent
        ? Notifications.AndroidNotificationPriority.MAX
        : Notifications.AndroidNotificationPriority.HIGH,
      color: "#2F50E4",
    },
    // The same deterministic id the feed uses, so the OS replaces an earlier
    // copy of the same signal instead of stacking duplicates.
    identifier: item.id,
    // THE CHANNEL GOES ON THE TRIGGER, NOT ON `content`.
    //
    // `ChannelAwareTriggerInput` — `{ channelId }` alone — is expo's way of
    // saying "deliver now, on this channel"; it is still immediate, exactly as
    // `trigger: null` is. A `channelId` set on `content` is silently dropped,
    // and the notification lands in
    // `expo_notifications_fallback_notification_channel` instead, which is how
    // this was first written and what a `dumpsys notification` on a real
    // handset showed on 2026-09-12. Nothing fails loudly: the banner appears,
    // so the only symptom is that the Leads/Reminders split does not exist, the
    // importance and vibration pattern configured in `configurePush` never
    // apply, and a rep silencing "Reminders" silences their leads with it.
    trigger:
      Platform.OS === "android"
        ? { channelId: REMINDER_KINDS.has(item.kind) ? CHANNEL_REMINDERS : CHANNEL_LEADS }
        : null,
  })
}

/**
 * Post a sample notification, from the Notifications settings screen.
 *
 * Not a developer toy: "I am not getting alerts" is the single hardest support
 * question to answer on Android, because the answer can be the app's own switch,
 * the OS permission, a silenced channel, a battery optimiser, or Do Not Disturb —
 * and five of those six are invisible from inside the app. One tap that either
 * appears in the shade or does not splits that question in half, and the sample
 * carries the real Call / WhatsApp buttons so the whole path is what gets tested,
 * not just the banner.
 *
 * Returns false when the OS refused permission outright, so the caller can say
 * something more useful than "sent".
 */
export async function sendTestNotification(phone = ""): Promise<boolean> {
  if (!(await ensurePushPermission())) return false
  await presentNotification({
    id: TEST_NOTIFICATION_ID,
    kind: "enquiry-new",
    module: "Test",
    icon: "enquiry",
    tone: "primary",
    when: new Date().toISOString(),
    urgent: false,
    title: "Test notification",
    body: "This is what a new lead looks like.",
    facts: [],
    customerName: "Ortex Industries",
    // The rep's OWN number, when the profile carries one: the sample then shows
    // the real Call / WhatsApp buttons, and pressing one rings the only person
    // it is safe to ring — themselves. With no number on the profile the sample
    // falls back to the plain category, which still proves the banner.
    phone,
    // Tapping it goes to the Notifications list. The engine special-cases this
    // id, because there is no record behind a sample and a detail screen opened
    // on a fake row is a worse answer than no answer.
    target: { screen: "EnquiryDetail", id: TEST_NOTIFICATION_ID },
    actions: [{ id: "open", label: "Open" }],
    push: {
      title: "Ortex notifications are working",
      body: "A real lead shows the customer, what they want, their number, and Call / WhatsApp buttons here.",
    },
  })
  return true
}

/** Clear the shade — used when the rep marks everything read in the app. */
export async function dismissAll(): Promise<void> {
  await Notifications.dismissAllNotificationsAsync().catch(() => {})
  await Notifications.setBadgeCountAsync(0).catch(() => {})
}

export async function dismissNotification(id: string): Promise<void> {
  await Notifications.dismissNotificationAsync(id).catch(() => {})
}

export async function setBadge(count: number): Promise<void> {
  await Notifications.setBadgeCountAsync(count).catch(() => {})
}

/** The action the rep tapped, or "open" for the notification body itself. */
export function actionFromResponse(response: Notifications.NotificationResponse): NotificationActionId {
  const id = response.actionIdentifier
  if (id === "call" || id === "whatsapp") return id
  return "open"
}

export function payloadFromResponse(
  response: Notifications.NotificationResponse,
): PushPayload | null {
  const data = response.notification.request.content.data as Record<string, unknown> | undefined
  if (!data) return null
  if (data.target) return data as unknown as PushPayload
  // A server-sent lead: FCM data is a flat map of strings, so the target
  // arrives as two fields (see Ortex.Admin supabase/functions/push-notify).
  if (typeof data.targetScreen === "string" && typeof data.targetId === "string") {
    return {
      id: String(data.id || ""),
      target: { screen: data.targetScreen, id: data.targetId } as PushPayload["target"],
      phone: String(data.phone || ""),
      title: String(data.title || ""),
    }
  }
  return null
}

export { Notifications }
